- src/Client.php
Currently the `process` call may hang forever, when for example the connection is disrupted.
> Replace PHP_INT_MAX with config timeout in Client

- src/Message/Info.php
- tests/FactoryTest.php
In our setup, Invalid property domain for message Basis\Nats\Message\Info error is thrown when this library connects to a leaf node.
Domain is not a valid option for INFO, but the go source code includes it with some additional attributes:
https://github.com/nats-io/nats-server/blob/95caa6ba363c204f2d33189a85fa119b0f2c5190/server/server.go#L61
In my understanding only the first block of attributes are required, because those are send to the client.
A future proof solution could be to remove the `InvalidArgumentException` from `Prototype`, and allow for unknown attributes as well.
> Update Info class based on the Nats source

- README.md
- docker/certs/.gitignore
- docker/docker-compose.yml
- docker/scripts/generate-certs.sh
- src/Client.php
- src/Configuration.php
- tests/Functional/ClientTest.php
Updated the connection logic to convert the socket to TLS 1.2 when the server INFO message has the tls_required property set to true. If the INFO message has the tls_verify property set to true the code sets the client side TLS certificates for client authentication based on tls connection settings. 
The new connection settings options are: 
- tlsKeyFile
- tlsCertFile
- tlsCaFile 
Nats instructions for configuring a cluster with TLS: https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/tls_mutual_auth
```
use Basis\Nats\Client;
use Basis\Nats\Configuration;
// this is default options, you can override anyone
$configuration = new Configuration([
'host' => 'localhost',
'jwt' => null,
'lang' => 'php',
'pass' => null,
'pedantic' => false,
'port' => 4222, …
```
> Added support for TLS 1.2 including client cert verification.

- src/Message/Msg.php
- src/Message/Payload.php
- tests/Functional/StreamTest.php
When JetStream message is pulled from the stream `replyTo` field contains some useful information.
This PR parse message timestamp in nanoseconds - the time when message was pushed to the stream.
Inspired by [js client for NATS](https://github.com/nats-io/nats.deno/blob/fd397655e390b36cd52119ec80ce3446f54cb614/nats-base-client/jsmsg.ts#L41)
> feat: parse jet stream message timestamp

- src/Consumer/Configuration.php
- tests/Functional/DeliveryPolicyTest.php
There are two delivery policies for JetStream consumers which require additional options (`DeliveryPolicy::BY_START_SEQUENCE` and `DeliveryPolicy::BY_START_TIME`)
This PR adds setters for those options.
> feat: add methods to set delivery policy options

- src/Client.php
- tests/Functional/ClientTest.php
This PR add additional read timeout check and throw exception if client didn't receive any data from NATS too long.
Why this check is important?
I'm using NATS with JetStream and in rare cases I run into situation when NATS doesn't send any data. To catch situation like this there should be few factors:
- There are no messages to read in the stream and message request timeout is not reached (no request timeout message from NATS)
- Ping time is not reached on the server side so client does not receive `PING` message
- Ping time is not reached on the client side so client does not send `PING` message and does not receive `PONG` message OR client send `PING` message but does not receive `PONG` message in time because of delay.
When all conditions are met client fails to read any data from …
> feat: check read timeout

- src/Client.php
- src/Consumer/Consumer.php
This PR improves jet stream message processing removing redundant sleep when ping message was received or message request was expired
> feat: do not call empty handler on ping message

- src/Consumer/Consumer.php
- src/KeyValue/Bucket.php
- tests/Functional/KeyValue/BucketTest.php
> feat: Fetching all stored key value pairs in bucket

- tests/Functional/StreamTest.php
- tests/Functional/SubjectTest.php
getting value of _**num_pending**_ immediately after publish may returns wrong value.
Added retries for getting of 'num_pending'
Existing delays (_usleep_) in code were not deleted.
> [Tests fix]: Add retries for getting of 'num_pending'

- src/Client.php
Hi,
We don't run our handlers within `Consumer::handle` scope, instead we'd like to subscribe, yield N messages to the outside, then unsubscribe.
This is currenly impossible as we dont get the handler result back from `process()`
This enables doing eg.:
```
subscribe(fn () => message)
yield process()
unsubscribe()
```
cc @nekufa
> Expose handler result

- src/Client.php
Hello
Since the last version we can't publish empty string or null as a payload we will get the following error : 
```
Message: Typed property Basis\Nats\Message\Msg::$payload must not be accessed before initialization
File: /opt/project/BACKEND/vendor/basis-company/nats/src/Client.php
Line: 344
Trace: #0 /opt/project/BACKEND/vendor/basis-company/nats/src/Client.php(323): Basis\Nats\Client->onMessage(Object(Basis\Nats\Message\Msg), true)
```
Thanks for the work for this library :)
> Allow empty message

- src/Consumer/Configuration.php
> Add missing Consumer.setMaxDeliver/setMaxWaiting

- src/Connection.php
makes sure stack trace is available in logs
> expose socket exception in logs

- README.md
Corrected a typo in the variable name within the code example in the README documentation, ensuring consistency and preventing confusion for readers following the example. The typo fix changes 'greater' to 'greeter' in the variable dump line.
> Fix typo in README.md variable reference

- src/Stream/Stream.php
- tests/Functional/StreamTest.php
Added $JS.API.STREAM.PURGE.* - "Purges all of the data in a Stream, leaves the Stream"
purgeQueue is one of the [queue-interop](https://github.com/queue-interop/queue-interop) operations on queue
```php
public function purgeQueue(Queue $queue): void;
```
Adding PURGE will improve functionality of NatsJS transport (in development) in [php-enqueue](https://github.com/php-enqueue/enqueue) (implementation of queue-interop)
> Add PURGE stream

- src/Client.php
took me some time to realize stream was missing due underlying error
```
"error":{"code":400,"err_code":10005,"description":"no suitable peers for placement"}
```
but this never threw, now it does :)
for future reference: never use php magic methods :)
> fix error checking

- README.md
getPayload was mentioned in the pubsub example which didn't exist; read public property instead.
> Msg's getPayload reference removed, read public property instead.

- src/Client.php
- src/Connection.php
- tests/Functional/ClientTest.php
- tests/Functional/SubjectTest.php
Fixes basis-company/nats.php/#30
Created this issue since we also need to be able to close the connection in environments where php as is run as a daemon
> Add option to unsubscribe consumers and close connection 

- src/Message/Msg.php
- src/Message/Nak.php
- src/Message/Progress.php
- tests/Functional/StreamTest.php
- tests/Unit/Message/AckTest.php
- tests/Unit/Message/NakTest.php
- tests/Unit/Message/ProgressTest.php
Currently the payload generated to publish a NAK is wrong and does not result of actually nak-ing a message. 
According to the documentation, acknowledgment is done only by sending the reply string, but Ack prorotype here generates adds +ACK command in the payload
it results in a mesasge like this
``PUB $JS.ACK.sample-stream.psub.3.1.21.1719946162089866350.0  +ACK 0``
but the actual that is required is this
``PUB $JS.ACK.sample-stream.psub.3.1.21.1719946162089866350.0  0``
When generating NAKs, the problem continues. It generates a message like this 
``PUB $JS.ACK.sample-stream.psub.3.1.21.1719946162089866350.0  -NAK 21\r\n{"delay": 5000000000}``
but the expexted nack string is 
``PUB $JS.ACK.sample-stream.psub.2.1.11.1719946162089866350.0  26\r\n-NAK {"delay": 5000000000}``
The -NAK …
> fix ack payload rendering

- src/Connection.php
- tests/Performance/PerformanceTest.php
During a try to implement Object store around this lib, me and my team stumbled on a performance issue. Trying to substring from few hundred kilobytes worth of text was quite heavy and was slowing down the push quite a lot. 
Here is the performance test done with the old substring: 
```
[docker://php-8.1-cli:latest/]:php /opt/project/vendor/phpunit/phpunit/phpunit --configuration /opt/project/phpunit.xml.dist --filter "/(Tests\\Performance\\PerformanceTest::testPerformanceWithBigMessages)( .*)?$/" --test-suffix PerformanceTest.php /opt/project/tests/Performance --teamcity
Testing started at 15:45 ...
PHPUnit 9.6.19 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.1.29
Configuration: /opt/project/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has …
```
> Improve performance for large payloads

- README.md
- src/Configuration.php
- src/Connection.php
Makes nats.php compatible with server configuration `handshake_first: true` see documentation:
https://docs.nats.io/running-a-nats-service/configuration/securing_nats/tls#tls-first-handshake
golang implementation: https://github.com/nats-io/nats.go/pull/1433
> add tlsHandshakeFirst to support nats servers which do not allow INFO in clear text
